# Generated by Django 5.1.2 on 2024-10-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
