# Generated by Django 5.1.2 on 2024-10-23 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_customuser_staff_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff_member',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_teacher',
        ),
    ]
