# Generated by Django 5.1.2 on 2024-10-23 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
