# Generated by Django 5.1.2 on 2024-10-23 02:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Please enter a valid subject name.', regex='^[a-zA-Z]+(?: [a-zA-Z]+)*$')], verbose_name='Subject Name')),
                ('subject_code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid 3-digit subject_code.', regex='^\\d{3}$')], verbose_name='Subject Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('class_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Class ID')),
                ('class_name', models.CharField(default='', max_length=64, unique=True, verbose_name='Class Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('assigning_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.subject'),
            preserve_default=False,
        ),
    ]
