# Generated by Django 5.1.2 on 2024-10-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_subject_studentclass_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=3, unique=True, verbose_name='Subject Code'),
        ),
    ]
