# Generated by Django 5.1.2 on 2024-10-24 01:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_customuser_student_alter_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('monthly_fee', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Please enter a valid fee amount.', regex='^\\d+$')], verbose_name='Monthly Fee')),
                ('admission_fee', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Please enter a valid fee amount.', regex='^\\d+$')], verbose_name='Admission Fee')),
                ('first_quarter_exam_fee', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Please enter a valid fee amount.', regex='^\\d+$')], verbose_name='First quarter exam fee')),
                ('half_year_exam_fee', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Please enter a valid fee amount.', regex='^\\d+$')], verbose_name='Half year exam fee')),
                ('second_quarter_exam_fee', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Please enter a valid fee amount.', regex='^\\d+$')], verbose_name='Second quarter exam fee')),
                ('annual_exam_fee', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Please enter a valid fee amount.', regex='^\\d+$')], verbose_name='Annual year exam fee')),
                ('board_reg_fee', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Please enter a valid fee amount.', regex='^\\d+$')], verbose_name='Board registration fee')),
                ('board_fee', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Please enter a valid fee amount.', regex='^\\d+$')], verbose_name='Board fee')),
                ('admit_card_fee', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Please enter a valid fee amount.', regex='^\\d+$')], verbose_name='Admit card fee')),
                ('practical_1_fee', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Please enter a valid fee amount.', regex='^\\d+$')], verbose_name='Practical 1 fee')),
                ('practical_2_fee', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Please enter a valid fee amount.', regex='^\\d+$')], verbose_name='Practical 2 fee')),
                ('practical_3_fee', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Please enter a valid fee amount.', regex='^\\d+$')], verbose_name='Practical 3 fee')),
                ('practical_4_fee', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Please enter a valid fee amount.', regex='^\\d+$')], verbose_name='Practical 4 fee')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.studentclass')),
            ],
            options={
                'verbose_name': 'Fee Structure Detail',
                'verbose_name_plural': 'Fee Structure Details',
            },
        ),
    ]
