# Generated by Django 5.1.2 on 2024-10-24 01:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_students_email_alter_students_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='monthly_fee',
            field=models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Please enter a valid fee amount.', regex='^\\d+$')], verbose_name='Total Monthly Fee'),
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, default='0', max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number.', regex='^[6-9]\\d{9}$')], verbose_name='Phone Number')),
                ('monthly_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly Fee')),
                ('admission_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Admission Fee')),
                ('first_quarter_exam_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='First quarter exam fee')),
                ('half_year_exam_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Half year exam fee')),
                ('second_quarter_exam_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Second quarter exam fee')),
                ('annual_exam_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Annual year exam fee')),
                ('board_reg_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Board registration fee')),
                ('board_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Board fee')),
                ('admit_card_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Admit card fee')),
                ('practical_1_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Practical 1 fee')),
                ('practical_2_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Practical 2 fee')),
                ('practical_3_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Practical 3 fee')),
                ('practical_4_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Practical 4 fee')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.studentclass')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.students')),
            ],
            options={
                'verbose_name': 'Fee Payment Detail',
                'verbose_name_plural': 'Fee Payment Details',
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('transaction_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transaction Date')),
                ('transaction_type', models.CharField(choices=[('Fee Pay', 'Fee Payment'), ('Vehicle Pay', 'Vehicle Fee'), ('Exam Fee', 'Exam Fee'), ('Admission Fee', 'Admission Fee')], default='Fee Pay', max_length=50, verbose_name='Transaction Type')),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Net Banking', 'Net Banking'), ('UPI', 'UPI')], default='Cash', max_length=50, verbose_name='Payment Mode')),
                ('amount_paid', models.CharField(default=0, max_length=50, verbose_name='Paid Amount')),
                ('reference_no', models.CharField(blank=True, default='', max_length=10, verbose_name='Reference Number')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='Remarks')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.students')),
            ],
            options={
                'verbose_name': 'Transaction History',
                'verbose_name_plural': 'Transaction Histories',
            },
        ),
    ]
